//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2024 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2024.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76309   75213
        ///79731   28444
        ///29583   71339
        ///60992   99148
        ///34680   74530
        ///45691   82519
        ///55358   22047
        ///95523   45384
        ///37661   82208
        ///33464   91461
        ///26897   96393
        ///76556   76554
        ///82316   98880
        ///92079   23082
        ///55539   10033
        ///65931   66060
        ///98880   60464
        ///19348   41458
        ///72003   84074
        ///78401   78856
        ///53187   72003
        ///65201   71211
        ///45971   12776
        ///45911   26854
        ///37527   13462
        ///28891   28444
        ///82801   81076
        ///29496   21971
        ///81662   12472
        ///89956   51107
        ///92833   22498
        ///23135   19348
        ///33661   51107
        ///48499   81114
        ///53 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 901403454308767601987430010102103430787676
        ///812312567219458912376541023411212321096787
        ///765403498012307433489432196520303234585898
        ///012354321087216524570343787434454100674301
        ///985467891096987019601234378976569981001210
        ///876654102345106508710765234789678972343454
        ///798783287765278710789820105678710169858763
        ///687690196894369821890112344589801258769012
        ///501543285210152152721201453078987340150103
        ///432457894101043043630328762101456498201232
        ///870326543232032154549419234652343567398341
        ///9612100123431290696085001657 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 127 680267 39260 0 26 3553 5851995.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYYYYYYYEJJEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGGCCCCCCCCCCWWCCLLLKKKKJKKKKKKFFFFFFFBBBBBBBBBBBAEEEEEEEEEEEEPPPPPPPPPOOOOZYYYZZZZZZAAUUUUUUUUUUUU
        ///YYYYYYYYNEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGCCCCCCCCCCCCCCCLLLLKKKKKKKKKKKFFFFFBBFBOBBBBBBBBBEEEEEEEEEEEPPPPPPOOOOOOOZZZZZZZZZZZAAUKUUUUUUUUU
        ///YYYYYYNNNNYEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGGCCCCCCCCCCCCCCCCLKKKKKKKKKKKKFFFFFFFFBBBBBBBBBBBBEEEEEEEEPPPPPPPOOOOOOOOOZZZZZZZZZUUUUUUUUUUUUUU
        ///YYYNNNNNNNEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGVVVVCCCCCCCCCRREEEEKKKKKKKKKKKKFFFFFFXFBBBBB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 12 15 18 19 18
        ///84 86 88 89 92 92
        ///18 19 21 23 24 25 29
        ///56 59 60 61 63 66 73
        ///11 13 15 13 15
        ///36 38 36 39 42 43 40
        ///21 22 23 21 21
        ///35 37 38 39 37 41
        ///56 58 55 57 58 60 61 68
        ///77 78 80 80 83 85 88 89
        ///79 81 82 82 83 80
        ///89 90 91 91 91
        ///69 71 73 73 76 78 82
        ///2 4 5 8 8 13
        ///60 63 67 70 72 73 74 75
        ///15 16 18 22 19
        ///18 21 25 28 31 31
        ///58 61 65 66 67 71
        ///50 53 56 58 61 63 67 74
        ///51 54 56 58 59 62 67 70
        ///78 81 82 84 90 89
        ///62 64 65 71 73 73
        ///68 71 76 79 81 85
        ///23 25 30 32 34 36 37 44
        ///68 66 67 69 72 73 76
        ///52  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; mul(382,128)select(){*who(710,947)mul(117,325)?$#from()/select()mul(829,251)}@mul(17,183)(:*when()}?+,what()mul(911,142)[:&gt;)who(824,820)/mul(199,484) when()mul(325,240))select()$~?&apos;from(387,163)&gt;what()@mul(920,723)where()}(#what()&lt;who() !mul(274,899)what()mul(664,836)}~who();how()who(537,994)/(?]mul(257,635)^when()don&apos;t()!what()}where()#:when()&gt;&apos;where()mul(360,222),when()@&amp;&lt;^mul(268,245){{)%:from()&lt;#mul(936,776)$select()!mul(474,825)how()}~mul(484,39)!?:@[*&lt;mul(357,805)how()mul(261,810) {$&gt;mul(306,422)$wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMMMXMASMSSSMSMMSAMXSSMMSXMMAMXMXXXSMMSXXAMAASMSSMSSSMSASMMMXSXSMMSSSMSMXSXMAMAAXAXMMAMXMMMMSXSASMXMASAAMAMXMXAMAXMAXAXSAMSMXMMMAMAASASXMAMX
        ///SAMSAMXSAAAAXMASXXMAXAAAXMSMMMSSMMMXAAMMSMASMMMAMAAAAASASAXSAMXSXMAAMAAMAMASAMXSMMMSMAMASAMXAAAAMXAMXMAMSAMAMMAMXMXMASMAXMXAAMASAMMSMASAMSSM
        ///SAMMMMAMMMSMMMSMMMMMSSMMXXSAAMAAAMMXMMSAMMAMAAMASMXSMMMAMAXMASAXAMMSMXAMMMAMAMAAAAAMAASMSXSMMSMSMSSMMXAMSASXSAAMXSSXMXAMXSMSMSASAXSAMXMAMAAX
        ///MXMAXMXSAXAMXMMAMAAMXMASMASMMMSSMMSASAMASMASXMMAXAMXMXMAMXMAAMMSSMAXMMSASMSMAMXSSMSSSM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39|46
        ///23|35
        ///23|31
        ///25|99
        ///25|35
        ///25|41
        ///32|81
        ///32|75
        ///32|94
        ///32|98
        ///24|44
        ///24|68
        ///24|83
        ///24|85
        ///24|56
        ///31|41
        ///31|82
        ///31|49
        ///31|35
        ///31|73
        ///31|33
        ///44|29
        ///44|62
        ///44|26
        ///44|61
        ///44|79
        ///44|31
        ///44|72
        ///35|94
        ///35|32
        ///35|81
        ///35|17
        ///35|56
        ///35|73
        ///35|61
        ///35|16
        ///77|33
        ///77|82
        ///77|61
        ///77|68
        ///77|16
        ///77|85
        ///77|74
        ///77|84
        ///77|56
        ///28|79
        ///28|75
        ///28|95
        ///28|24
        ///28|39
        ///28|62
        ///28|21
        ///28|35
        ///28|49
        ///28|27
        ///26|77
        ///26|99
        ///26|41
        ///26|35
        ///26|49
        ///26|33
        ///26|39
        ///26|16
        ///26|83
        ///26|24
        ///26|84
        ///11|41
        ///11|43
        ///11|25
        ///11|83
        ///11|79
        ///11|31
        ///11|46
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......#.............#.....................#..#.........................................................#.................#.#......
        ///.................................#.....#............#........................................#.................................#..
        ///..................#.#.....#........#.#...#.....#..............#................#..#....................................#..#.......
        ///.#....#......................#..........................................................................#......#.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37603097701038: 475 8 68 9 9 5 878 38 3
        ///740556: 418 9 4 4 3 1 9 7 5 12 9
        ///41216: 2 8 8 46 7
        ///30984320: 1 928 416 840 80
        ///31422162: 619 401 2 70 44
        ///6593961: 94 19 9 4 7
        ///243973: 7 230 6 97 3
        ///553110: 5 6 1 49 7 1 13
        ///569: 567 1 2
        ///26339: 928 66 19 26
        ///126563: 12 2 9 56 4
        ///909583: 92 5 38 59 89 5
        ///1870: 1 477 993 98 302
        ///716: 5 72 58 382 1 17 181
        ///59398283: 75 1 877 79
        ///8974471341: 9 860 8 3 99 8 552 9 61
        ///1547232: 83 266 70 950 822
        ///38491788: 4 3 18 4 81 4 5 2 2 23 89
        ///1802: 5 30 71 17
        ///21013: 42 236 2 8 8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..........K........................A..............
        ///.K................................A...............
        ///......................................D.....A.....
        ///....................................6............D
        ///..................................................
        ///.............................d....................
        ///.........4.e.......................DT.B...........
        ///....................d.....D......A...........B....
        ///.............K....................................
        ///...........................k................ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97846550507294855731177421467823267490534984668852323184698155618476911155792191264249136182706883479731528189191286457137757170825677127128482062777734113363874581334426904061717087667027812156225465188635143731382061562664599297597323547091379178595315724344422519417211517532612637404185471761246315334658408046576493937642391769271844386138256174337787488134569264399282473896184793238986363440886645397637487339586544454152429390327595809234401197313678866619682362502627355525147095125525552737543667539282 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
    }
}
